apiVersion: v1
stringData:
  BACKSTAGE_NOTIFICATIONS_URL: http://backstage-backstage.rhdh-operator
  NOTIFICATIONS_BEARER_TOKEN: ""
  ONBOARDING_SERVER_URL: http://user-onboarding-server.sonataflow-infra:8080
kind: Secret
metadata:
  creationTimestamp: null
  name: user-onboarding-creds
